### ISSUE TITLE
Cocoapods support?

### ISSUE THREAD

**Issue by anonrig** [mauron85/react-native-background-geolocation#143]
Do you plan to add cocoapods support to react-native-background-geolocation?

**Comment by mauron85** [comment]
I don't think this is necessary. It will complicate install phase.

**Comment by juliancorrea** [comment]
Please explain what benefit do you see in using cocoapods. ????
Serious?

**Comment by mauron85** [comment]
I mean: "What benefit do you see in using cocoapods for this project."  Not questing cocoapods in general.

**Comment by juliancorrea** [comment]
Some libs like react-native-maps ( https://github.com/react-community/react-native-maps/blob/master/docs/installation.md ), uses cocoapods, among others. 
It's very common uses the react-native-maps with some gps background location lib. So, does make sense uses cocoapods because this and also the reasons known.
