### ISSUE TITLE
Android App Crash after some time 

### ISSUE THREAD

**Issue by rulgf** [mauron85/react-native-background-geolocation#149]
## Your Environment

* Plugin version: 0.4.1
* Platform: Android
* OS version: Android 6.0 Marshmallow
* Device manufacturer and model: Sony Xperia E5 
* React Native version: 0.47
* Plugin configuration options: {
  desiredAccuracy: 10,
  stationaryRadius: 50,
  distanceFilter: 50,
  notificationTitle: 'Title',
  notificationText: 'Text',
  debug: false,
  startOnBoot: false,
  stopOnTerminate: false,
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
  interval: 5000,
  fastestInterval: 5000,
  activitiesInterval: 5000,
  stopOnStillActivity: false,
}

* Link to your project: N/A

## Context
After some time of the app running background or foreground the app stops and close

## Expected Behavior
The app keeps running and working foreground and background

## Actual Behavior
The App crash with fatal Exception:
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask

## Context
I'm trying to send the user location each 5 seconds.

**Comment by kholiavko-roman** [comment]
@rulgf, after what time you app is crashing ?
I have a problem with some users, they stops update automatically after a long time. But I don't know what exactly happens, because I can't see the logs remotely.

**Comment by rulgf** [comment]
@kholiavko-roman around 20 - 30 minutes

**Comment by rohithramachandran** [comment]
This happens for me too. Here is the complete logs

```
E/AndroidRuntime( 5365): java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@52baff80 rejected from java.util.concurrent.ThreadPoolExecutor@527ed978[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 40]
E/AndroidRuntime( 5365): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
E/AndroidRuntime( 5365): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
E/AndroidRuntime( 5365): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
E/AndroidRuntime( 5365): 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
E/AndroidRuntime( 5365): 	at com.marianhello.bgloc.LocationService.postLocation(LocationService.java:499)
E/AndroidRuntime( 5365): 	at com.marianhello.bgloc.LocationService.handleLocation(LocationService.java:402)
E/AndroidRuntime( 5365): 	at com.marianhello.bgloc.AbstractLocationProvider.handleLocation(AbstractLocationProvider.java:85)
E/AndroidRuntime( 5365): 	at com.marianhello.bgloc.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:108)
E/AndroidRuntime( 5365): 	at com.google.android.gms.internal.zzcfj.zzu(Unknown Source)
E/AndroidRuntime( 5365): 	at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source)
E/AndroidRuntime( 5365): 	at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source)
E/AndroidRuntime( 5365): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5365): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5365): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 5365): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5365): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5365): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5365): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5365): 	at dalvik.system.NativeStart.main(Native Method
```

**Comment by mauron85** [comment]
Thank you for the logs. I'll take look at it.

**Comment by mauron85** [comment]
Probably duplicate of https://github.com/mauron85/react-native-background-geolocation/issues/68.

Maybe too many parallel active AsyncTasks.

**Comment by mauron85** [comment]
>AsyncTask.THREAD_POOL_EXECUTOR cannot queue more that 128 tasks at a time. So if we submit more than that, an exception will be thrown.

https://medium.com/@arj.sna/android-multiple-asynctasks-78b2f847a2ec

In case server responses take significant time (eg. slow connection), queue limit is reached resulting to app crash with 
`RejectedExecutionException`.

**Comment by rulgf** [comment]
Thanks for the answer @mauron85! Yep I've already solved this some days ago. I think is server response problem,
To solve this I did 2 changes to my code:

- First I noticed that my configuration was pretty messed up and I let the `url` option as in the example (-_-')
- Also I noticed that I was calling BackgroundGeolocation.start() before my listeners where mounted. 

After these changes, everything works as expected. Awesome Plugin by the way

**Comment by VivekSharma-zymr** [comment]
Using the configuration below. Also, After 15-20 mins on Android POCO F1 App closes automatic from the background. Posting the location at every 30 seconds.

  desiredAccuracy: BackgroundGeolocation.LOW_ACCURACY, //Desired accuracy in meters. Possible values [HIGH_ACCURACY, MEDIUM_ACCURACY, LOW_ACCURACY, PASSIVE_ACCURACY]. Accuracy has direct effect on power drain. Lower accuracy = lower power drain.
  stationaryRadius: 5, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
  distanceFilter: 10, // 10, meter , The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
  notificationTitle: 'KX Trucker',
  notificationText: 'Tracking your journey',
  notificationsEnabled: true,
  debug: false,
  notificationIconSmall: "",
  notificationIconLarge: "",
  startOnBoot: false, //Start background service on device boot.
  startForeground: true, //Android only, Allow location sync service to run in foreground state. Foreground state also requires a notification to be presented to the user.
  stopOnTerminate: isAndroid ? false : true, //Enable this in order to force a stop() when the application terminated (e.g. on iOS, double-tap home button, swipe away the app).
  locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
  interval: 29000, // android only, The minimum time interval between location updates in milliseconds.
  fastestInterval: 29000, //android only, Fastest rate in milliseconds at which your app can handle location updates.
  activitiesInterval: 29000, //android only,Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
  stopOnStillActivity: false,
  notificationIconColor: "Red",
  enableHighAccuracy: true,
  pauseLocationUpdates: false,
  saveBatteryOnBackground: false,
  maxLocations: 10000,
  //Will uncomment later below 3 linew, If our B.E support locations array sent to server at once
  syncThreshold: 100, //Specifies how many previously failed locations will be sent to server at once
  // syncUrl: '',
  syncUrl: "",
  url: '',
  // customize post properties
  postTemplate: { "speed": "@speed", "time": "@time", "locationProvider": "@locationProvider", "longitude": "@longitude", "radius": "@radius", "bearing": "@bearing", "accuracy": "@accuracy", "provider": "@Provider", "latitude": "@latitude", "altitude": "@altitude" }
