### ISSUE TITLE
Stop location updates when device is stationary

### ISSUE THREAD

**Issue by theebi** [mauron85/react-native-background-geolocation#220]
We have a react-native app which drains a lot of battery in background. And I can see my application listed as high battery usage app in the settings. I can see an option saying stopOnStillActivity. I have set it to true but still client says his phone sends location updates when it's in the same place. I'm attaching my config with this.

  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
  stationaryRadius: 50,
  distanceFilter: 100,
  debug: false,
  startOnBoot: true,
  stopOnTerminate: false,
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
  interval: 10000,
  fastestInterval: 10000,
  activitiesInterval: 10000,
  stopOnStillActivity: true

**Comment by mauron85** [comment]
Sorry this incomplete report. Missing device info, OS info ... See issue template. Without it I can help.

**Comment by gokulanath** [comment]
We are using the stationary radius to prevent the repeated coordatinates recorded for the device. But even when stationary radius given, we are getting the dupliate coordinates with in the staionary radius. Also it happens when we try to switching the app  from background to foreground.

### Environment
- Plugin version: v0.5.0-alpha.32
- Platform: Android
- OS version: 8.1.0
- Device manufacturer and model: One Plus 5T
- React Native version: 0.55.4

      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 100,
      distanceFilter: 50,
      notificationTitle: 'Background Tracking',
      notificationText: 'enabled',
      debug: false,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: true,
      maxLocations: 5000

1. ![image](https://user-images.githubusercontent.com/6873254/42105243-7f708b18-7b84-11e8-90b1-3dcf1e1cef29.png)
2. ![image](https://user-images.githubusercontent.com/6873254/42105290-a46a83e2-7b84-11e8-9115-f244eb035ecf.png)
