### ISSUE TITLE
Remove the device Notification

### ISSUE THREAD

**Issue by BigPun86** [mauron85/react-native-background-geolocation#3]
Is there a easy way to avoid the Notification above?

![bgtracking](https://cloud.githubusercontent.com/assets/7880624/17213902/b8182ff6-54d6-11e6-82b2-6eebb9fea8cf.png)

**Comment by mauron85** [comment]
Yes option `startForeground: false`, but don't recommend to use it, as it will make plugin more vulnerable to OS kill.

**Comment by edencakir** [comment]
Set the debug flag false.

**Comment by edencakir** [comment]
Set debug false. #29

**Comment by Shhzdmrz** [comment]
@mauron85 is this comment still valid? If yes then why not to add it in the doc?

**Comment by mauron85** [comment]
@Shhzdmrz my comment is valid. From the docs: `startForeground: false` "if false location service will not be started in foreground and no notification will be shown."

**Comment by Shhzdmrz** [comment]
@mauron85 I am confused now `startForeground: false`, is it mean service will totally not started or just it will not show the notification in foreground? 
The screen having location service with config startForeground as true it never remove the screen even I kill the app and open it again the same screen will open and you are recommending not to use it, as it will make plugin more vulnerable to OS kill. I am not a native developer please briefly explain it.

**Comment by dengue8830** [comment]
it seems that it starts in background without a notification, `startForeground` flag just creates the notification and binds the service to it in order to prevent the service be killed by the system (that could be a definition of "service in foreground")

https://github.com/mauron85/background-geolocation-android/blob/19a9972b46eee4e176c6de3e523ce70e2b8d5fae/src/main/java/com/marianhello/bgloc/service/LocationServiceImpl.java#L358
