### ISSUE TITLE
geolocation stop in background for huawei smartphone 

### ISSUE THREAD

**Issue by invyctus92** [mauron85/react-native-background-geolocation#332]
Geolocation stop in background for huawei smartphone 
## Your Environment
for huawei smartphone  as p10 lite when the app goes into the background, after a while the operating system stops the geolocation. 

* Plugin version: "0.5.0-alpha.42",
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model: p10 lite
* React Native version:0.53.0
* Plugin configuration options: BackgroundGeolocation.configure({
      desiredAccuracy: 10,
      stationaryRadius: 50,
      distanceFilter: 50,
      debug: false,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false, // test per berto
      startForeground: true,
      notificationIconColor: "#e33",
      notificationIconLarge: "ic_launcher",
      notificationIconSmall: null,
      notificationTitle: "MUV",
      notificationText: "Background tracking",
      saveBatteryOnBackground: false,
      activityType: type === "Public" ? "AutomotiveNavigation" : "Fitness"
    });

is there a method to prevent the operating system kills the app in the background ?

**Comment by CallumCoombes** [comment]
This is a known battery optimisation 'feature' of many Android devices. Many manufacturers, including Huawei, add their own power managers and kill all background services as soon as screen is closed or app is no longer visible.

This even happens when it's a foreground service!

You have to get the user to manually whitelist the app from the settings, and example for many devices can be seen [here](https://bitbucket.org/copluk/acr/issues/607).

There is a permission related to this on Android, 'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS'. However, Google have been known to automatically ban apps that use this permission, so use it at your own risk.

**Comment by mauron85** [comment]
Yes, this is unfortunately rising up trend.

**Comment by clarissacarcha** [comment]
Having same issue with background location in Huawei phones. Is there a any solution other than REQUEST_IGNORE_BATTERY_OPTIMIZATIONS?

**Comment by walterdl** [comment]
@clarissacarcha did you solved it?
