### ISSUE TITLE
IOS 13 app crash on init

### ISSUE THREAD

**Issue by baierjak** [mauron85/react-native-background-geolocation#428]
## Your Environment

* Plugin version: 0.6.2
* Platform: iOS
* OS version: iOS 13
* Device manufacturer and model: iPHONE XS

* Running in Simulator: on real device
* React Native version:  "react-native": "0.59.8",
* Plugin configuration options: from example
* Link to your project:

## Context

On init screen with this library init crashes on IOS 13. Previous versions run without a problem and crashes.

**Comment by Alaa-Ben** [comment]
You're not respecting this though
<img width="303" alt="Capture d’écran 2019-09-24 à 15 05 34" src="https://user-images.githubusercontent.com/26058727/65514438-988c9700-dedd-11e9-8c24-ba98fdadfe4c.png">

**Comment by baierjak** [comment]
@Alaa-Ben That could be it. Thank you. But it will be really hard to move to 0.60.0 though haha :))

**Comment by Alaa-Ben** [comment]
@baierjak I just finished migrating to 0.61.1 literally a few minutes ago. It was a bit complicated true, specially with the androidx breaking change, but worth it i guess. The thing is, there is a bug in this background geolocation plugin that crashes apps for android 9. The bug is now fixed but only in 6.x, so migrating is mandatory if you want to use this plugin and not crash on android 9 :/

**Comment by Alaa-Ben** [comment]
Good luck ! The upgrade helper was pretty useful for me ;)
