### ISSUE TITLE
App crashes after 15-20 mins java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask

### ISSUE THREAD

**Issue by dinesh8055** [mauron85/react-native-background-geolocation#68]
## Your Environment

* Plugin version: v0.1.1
* Platform: iOS or Android: Android
* OS version: Ubuntu 16.10
* Device manufacturer and model: Nexus 5
* React Native version: 0.42.0
* Plugin configuration options: N/A

## Context

The app crashes after 15-20 mins. Maybe because of creating too many AsyncTasks?

## Debug logs

04-20 18:02:22.502 28065 28065 E AndroidRuntime: FATAL EXCEPTION: main
04-20 18:02:22.502 28065 28065 E AndroidRuntime: Process: com.goloaddriver, PID: 28065
04-20 18:02:22.502 28065 28065 E AndroidRuntime: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@a8794db rejected from java.util.concurrent.ThreadPoolExecutor@7774b78[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 19]
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService.postLocationAsync(LocationService.java:422)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService.handleLocation(LocationService.java:340)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at com.marianhello.bgloc.AbstractLocationProvider.handleLocation(AbstractLocationProvider.java:81)
04-20 18:02:22.502 28065 28065 E AndroidRuntime: 	at com.marianhello.bgloc.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:87)

**Comment by rulgf** [comment]
@dinesh8055 Could you resolve this issue? How?

**Comment by VivekSharma-zymr** [comment]
@mauron85 Using the configuration below. Also, After 15-20 mins on Android POCO F1 App closes automatic from the background. Posting the location at every 30 seconds.

  desiredAccuracy: BackgroundGeolocation.LOW_ACCURACY, //Desired accuracy in meters. Possible values [HIGH_ACCURACY, MEDIUM_ACCURACY, LOW_ACCURACY, PASSIVE_ACCURACY]. Accuracy has direct effect on power drain. Lower accuracy = lower power drain.
  stationaryRadius: 5, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
  distanceFilter: 10, // 10, meter , The minimum distance (measured in meters) a device must move horizontally before an update event is generated.
  notificationTitle: 'KX Trucker',
  notificationText: 'Tracking your journey',
  notificationsEnabled: true,
  debug: false,
  notificationIconSmall: "",
  notificationIconLarge: "",
  startOnBoot: false, //Start background service on device boot.
  startForeground: true, //Android only, Allow location sync service to run in foreground state. Foreground state also requires a notification to be presented to the user.
  stopOnTerminate: isAndroid ? false : true, //Enable this in order to force a stop() when the application terminated (e.g. on iOS, double-tap home button, swipe away the app).
  locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
  interval: 29000, // android only, The minimum time interval between location updates in milliseconds.
  fastestInterval: 29000, //android only, Fastest rate in milliseconds at which your app can handle location updates.
  activitiesInterval: 29000, //android only,Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
  stopOnStillActivity: false,
  notificationIconColor: "Red",
  enableHighAccuracy: true,
  pauseLocationUpdates: false,
  saveBatteryOnBackground: false,
  maxLocations: 10000,
  //Will uncomment later below 3 linew, If our B.E support locations array sent to server at once
  syncThreshold: 100, //Specifies how many previously failed locations will be sent to server at once
  // syncUrl: '',
  syncUrl: "",
  url: '',
  // customize post properties
  postTemplate: { "speed": "@speed", "time": "@time", "locationProvider": "@locationProvider", "longitude": "@longitude", "radius": "@radius", "bearing": "@bearing", "accuracy": "@accuracy", "provider": "@Provider", "latitude": "@latitude", "altitude": "@altitude" }
